### ISSUE TITLE
windows系统上编译出错

### ISSUE THREAD

**Issue by XingRay** [RapidAI/RapidOcrOnnx#26]
安装文档执行生成vs项目sln

报错输出如下:

"========请先参考README.md准备好编译环境========"

"========编译选项========"
"请注意：项目默认使用Release库，除非您自行编译Debug版的Onnxruntime和Opencv，否则请不要选择Debug编译"
"请输入编译选项并回车: 1)Release, 2)Debug"
1

"请注意：如果选择2)JNI动态库时，必须安装配置Oracle JDK"
"请选择编译输出类型并回车: 1)BIN可执行文件，2)JNI动态库，3)C动态库"
1

"引用的库类型: 1)静态CRT(mt), 2)动态CRT(md)"
"注意：范例工程默认集成mt版库"
1

"onnxruntime: 1)CPU(默认), 2)GPU(cuda), 3)GPU(DirectML)"
"注意：范例工程默认集成CPU版，CUDA版仅支持x64且需下载"
1

"请输入选项并回车: 0)ALL, 1)vs2019-x86, 2)vs2019-x64:"
2
cmake -G "Visual Studio 16 2019" -A "x64" -DOCR_OUTPUT="BIN" -DOCR_BUILD_CRT="True" -DOCR_ONNX="CPU" ..
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The C compiler identification is MSVC 19.29.30154.0
-- The CXX compiler identification is MSVC 19.29.30154.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
配置WINDOWS OnnxRuntime x64 路径: D:/code/opensource/ai/ocr/RapidAI/RapidOcrOnnx/onnxruntime-static/windows-x64
-- OnnxRuntime_LIBS: onnxruntime.lib
-- OnnxRuntime_INCLUDE_DIRS: D:/code/opensource/ai/ocr/RapidAI/RapidOcrOnnx/onnxruntime-static/windows-x64/include
配置WINDOWS OpenCV x64 路径: D:/code/opensource/ai/ocr/RapidAI/RapidOcrOnnx/opencv-static/windows-x64
-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc14
-- OpenCV STATIC: ON
CMake Warning at opencv-static/windows-x64/OpenCVConfig.cmake:190 (message):
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  CMakeLists.txt:52 (find_package)

CMake Error at CMakeLists.txt:52 (find_package):
  Found package configuration file:

    D:/code/opensource/ai/ocr/RapidAI/RapidOcrOnnx/opencv-static/windows-x64/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.

-- Configuring incomplete, errors occurred!
(base) PS D:\code\opensource\ai\ocr\RapidAI\RapidOcrOnnx>

**Comment by XingRay** [comment]
windows11 x64 系统
![1726754270843](https://github.com/user-attachments/assets/900f76d1-cf22-4d1f-aca3-6348181743f1)

**Comment by benjaminwan** [comment]
Found OpenCV Windows Pack but it has no binaries compatible with your configuration.
找到了opencv，但与当前系统不兼容，猜测是安装的VC++版本太低。

要兼容旧版vs2019，就去下载Release 里的Project_RapidOcrOnnx-1.2.2.7z, https://github.com/RapidAI/RapidOcrOnnx/releases/tag/1.2.2
