### ISSUE TITLE
[BUG]使用同一个OcrInit创建的句柄连续识别可能导致结果错误

### ISSUE THREAD

**Issue by aiqinxuancai** [RapidAI/RapidOcrOnnx#29]
使用OcrInit初始化后，将句柄存储，后续API均使用这个句柄。

比如前1-3张图片有文字并且识别正常，此时第4次给一张空白的图（纯白啥都没有写），OcrDetect会返回成功，OcrGetLen、OcrGetResult会获取到上一张识别成功并有文字的结果（即第3张）。

**Comment by aiqinxuancai** [comment]
[ImageCaches.zip](https://github.com/user-attachments/files/17290474/ImageCaches.zip)
比如这几张图片，我按照顺序识别，参数是:
```
                 padding = 15,
                 maxSideLen = 0,
                 boxScoreThresh = 0.618f,
                 boxThresh = 0.300f,
                 unClipRatio = 3.5f,
                 doAngle = 1,
                 mostAngle = 1
```
理论上只有638640021001895571这张图可以识别，其他未识别到任何文字，但实际上，如果第一张用638640021001895571，同一个句柄继续识别，均返回的是638640021001895571这张的结果

**Comment by benjaminwan** [comment]
同一个线程内不可以重复调用初始化。创建一个线程，仅调用一次init，然后多次调用detect。

**Comment by aiqinxuancai** [comment]
> 同一个线程内不可以重复调用初始化。创建一个线程，仅调用一次init，然后多次调用detect。

我意思就是这样，一次init多次detect

**Comment by benjaminwan** [comment]
明白了，这可能是缓存没清除造成的问题

**Comment by benjaminwan** [comment]
如果有办法修复，欢迎贡献pr。

**Comment by aiqinxuancai** [comment]
我找到了原因，因为OcrDetect的返回值是1字节，我在c#中直接定义bool或int均为4字节，所以调用OcrDetect始终返回成功。

c#中定义OcrDetect的返回值改为byte应该就可解决。

除非是c++直接拿头文件使用OCR_BOOL，其他语言还挺容易弄错的。
