### ISSUE TITLE
如何输出坐标

### ISSUE THREAD

**Issue by Frozen1084** [RapidAI/RapidOcrOnnx#3]
我不是程序员，用 AutoHotkey 脚本加载 RapidOcrOnnx.dll 来识别图片。
请问如何设置才能输出坐标，或者说 json 呢？
RapidOcrOnnx.dll 只有5个函数，好像没有一个是用于配置这些参数的。
OcrDetect() 最后输入的结构也没有配置输出结果的项。

还有，如何设置才能识别空格呢？比如中英混合时，英文前后都有空格，怎么识别出这些空格呢？

**Comment by benjaminwan** [comment]
RapidOcrOnnx.dll 没有输出坐标，只有文字结果。
这几个版本空格识别不正常：1.1.0、1.1.1、1.1.3。
请使用1.2.x版本

**Comment by Frozen1084** [comment]
谢谢。不能添加个输出坐标的选项吗？感觉内部是有坐标数据的，不需要什么格式，哪怕把坐标追加到输出字符串的后面都行。

**Comment by benjaminwan** [comment]
项目自带了一个中英文混合的图片用于测试，这图片是可以识别到空格的。
https://github.com/RapidAI/RapidOcrOnnx/blob/main/images/1.jpg

输出坐标后续可以考虑添加。

**Comment by Frozen1084** [comment]
那个图片不是真的中英混合。它只是同时有中英文而已。
真的混合应该是这个图片这种：
![avatar](https://i.imgur.com/i71lELi.jpeg)
这个图片里的空格一个也没识别出来。

**Comment by benjaminwan** [comment]
这个图片，现有的几个模型都试了，包括server、mobile v2和v3都不行，这应该与rec模型相关，所以无法通过调参数或改代码来改进。

但是可以尝试另一个项目，这也是我贡献的代码，除了模型不同，调用的代码基本上一样
https://github.com/benjaminwan/OcrLiteOnnx

**Comment by Frozen1084** [comment]
啊，谢谢，识别出空格了，而且速度比这个快了1/5。
不过也变得不准确了，漏掉了一些文字，多了些错误识别。

RapidOcrOnnx
```
OCR.space本地-企业图像和PDFOCR
OCR.Space是功能强大的基于服务器的OCR软件，用于自动文档捕获和PDF转换。使用OCR.spaceLocal
安装和托管我们流行的OCRAPI和可搜索PDF在自己的PC和/或数据中心内完全支持在AmazonAWSAMI
或MicrosoftAzure等虚拟化和云环境上安装。从技术上讲，本地OCR服务器与我们流行的在线OCRAPI服务
相同。从云切换到本地，反之亦然不需要更改代码。
本地版本与OCR.spacePROPDF计划具有相同的功能、相同的API参数和相同的OCR质量，但100%在本
地和离线运行-它从不连接互联网。
```

OcrLiteOnnx
```
OCR.space 本地
-企业图像和PDFOCR
OCR.space 是功能强大的基于服务器的 OCR软件，用于自动文档捕扶和 PDF 转换，使用 OCR.space Local
安装和托管我们流行的 OCR API和可搜索 PDF 在自己的 PC和/或数据中心内完全支持在 Amazon AWS AM
或 Microsot Azure 等虚拟化和云环境上安装。从技术上讲，本地 OCR 服务器与我们流行的在线 OCR API 服务
相同。从云切换到本地，反之亦然不需要更改代码
本地版本与.OCR.space PRO PDF 计划具有相同的功能、相同的 AP! 参数和相同的 OCR 质量，
地和离线运行-它从不连接互联网
```

**Comment by benjaminwan** [comment]
> 啊，谢谢，识别出空格了，而且速度比这个快了1/5。 不过也变得不准确了，漏掉了一些文字，多了些错误识别。
> 
> RapidOcrOnnx
> 
> ```
> OCR.space本地-企业图像和PDFOCR
> OCR.Space是功能强大的基于服务器的OCR软件，用于自动文档捕获和PDF转换。使用OCR.spaceLocal
> 安装和托管我们流行的OCRAPI和可搜索PDF在自己的PC和/或数据中心内完全支持在AmazonAWSAMI
> 或MicrosoftAzure等虚拟化和云环境上安装。从技术上讲，本地OCR服务器与我们流行的在线OCRAPI服务
> 相同。从云切换到本地，反之亦然不需要更改代码。
> 本地版本与OCR.spacePROPDF计划具有相同的功能、相同的API参数和相同的OCR质量，但100%在本
> 地和离线运行-它从不连接互联网。
> ```
> 
> OcrLiteOnnx
> 
> ```
> OCR.space 本地
> -企业图像和PDFOCR
> OCR.space 是功能强大的基于服务器的 OCR软件，用于自动文档捕扶和 PDF 转换，使用 OCR.space Local
> 安装和托管我们流行的 OCR API和可搜索 PDF 在自己的 PC和/或数据中心内完全支持在 Amazon AWS AM
> 或 Microsot Azure 等虚拟化和云环境上安装。从技术上讲，本地 OCR 服务器与我们流行的在线 OCR API 服务
> 相同。从云切换到本地，反之亦然不需要更改代码
> 本地版本与.OCR.space PRO PDF 计划具有相同的功能、相同的 AP! 参数和相同的 OCR 质量，
> 地和离线运行-它从不连接互联网
> ```

这两种模型，默认的输入参数是不一样的, boxScoreThresh, boxThresh, unClipRatio，主要是这几个参数

**Comment by Frozen1084** [comment]
不是的，我在测试时使用了统一参数。
```
param.padding :=50
param.maxSideLen :=1024
param.boxScoreThresh:= 0.5
param.boxThresh :=0.3
param.unClipRatio:= 1.6
param.doAngle :=1
param.mostAngle :=1
```

我测试了很多ocr方案。当前最准确的是tesseract-ocr，它不仅空格准确，连空行都识别出来了
```
OCR.space 本地 - 企业图像和 PDF OCR
	
OCR.space 是功能温大的基于服务器的 OCR 软件，用于自动文档捕获和 PDF 转换。使用 OCR.space Local

安装和托管我们流行的 OCR API和 可搜索 PDF 在自己的 PC 和/或数据中心内完全支持在 Amazon AWS AMI
或 Microsoft Azure 等虚拟化和云环境上安装。从技术上讲，本地 OCR 服务器与我们流行的在线 OCR API 服务
相同。 从云切换到本地，反之亦然不需要更改代码,

本地版本与 OCR.space PRO PDF 计划具有相同的功能、相同的 API 参数和相同的 OCR 质量，但 100% 在本
地和离线运行 - 它从不连接互联网,
```

**Comment by benjaminwan** [comment]
> 不是的，我在测试时使用了统一参数。
> 
> ```
> param.padding :=50
> param.maxSideLen :=1024
> param.boxScoreThresh:= 0.5
> param.boxThresh :=0.3
> param.unClipRatio:= 1.6
> param.doAngle :=1
> param.mostAngle :=1
> ```
> 
> 我测试了很多ocr方案。当前最准确的是tesseract-ocr，它不仅空格准确，连空行都识别出来了
> 
> ```
> OCR.space 本地 - 企业图像和 PDF OCR
> 	
> OCR.space 是功能温大的基于服务器的 OCR 软件，用于自动文档捕获和 PDF 转换。使用 OCR.space Local
> 
> 安装和托管我们流行的 OCR API和 可搜索 PDF 在自己的 PC 和/或数据中心内完全支持在 Amazon AWS AMI
> 或 Microsoft Azure 等虚拟化和云环境上安装。从技术上讲，本地 OCR 服务器与我们流行的在线 OCR API 服务
> 相同。 从云切换到本地，反之亦然不需要更改代码,
> 
> 本地版本与 OCR.space PRO PDF 计划具有相同的功能、相同的 API 参数和相同的 OCR 质量，但 100% 在本
> 地和离线运行 - 它从不连接互联网,
> ```

这两个项目不能用一样的参数，必须不一样。

**Comment by benjaminwan** [comment]
因为模型不同的关系，OcrLite的unClipRatio需要大一点
param.boxScoreThresh:= 0.6
param.boxThresh :=0.3
param.unClipRatio:= 2.0

**Comment by Frozen1084** [comment]
修改了参数，结果没有变化。

**Comment by benjaminwan** [comment]
试了一下，确实不行，有一个框置信度太低，把boxScoreThresh门限降低能框出来，但仍然不准确，这种图片还是做放大后再识别比较好(比如把长边放大到1024再识别就准确了)。
最早的版本有放大的步骤，但因为图片放大会增加识别时间，后来去掉了。

**Comment by Frozen1084** [comment]
RapidOcrOnnx有放大，而OcrLiteOnnx没有？

**Comment by benjaminwan** [comment]
两个项目的代码是一样的，都没有对图片做拉伸放大。

把图片缩小是为了加快整个识别过程，以及降低内存消耗。

目前的参数maxSideLen只是用于缩小图片尺寸，比如maxSideLen=1024时，那么图片的长边像素如果大于1024，就会把图片等比例缩小到1024。

如果图片长边本来就小于1024，则不会处理原图。

你提供的图片尺寸是667 × 208，所以是不处理原图的这种情况。

**Comment by Frozen1084** [comment]
谢谢。也就是说是否需要放大图片并没有确切的判断条件对吧。

不过我还是希望可以有个函数直接操作位图句柄，这样截图ocr就可以省掉保存图片并读取的步骤，可以快几十毫秒。
