### ISSUE TITLE
能提供一下1.2.1版本shared的编译方法吗？

### ISSUE THREAD

**Issue by yupd** [RapidAI/RapidOcrOnnx#4]

**Comment by benjaminwan** [comment]
是说 把这个项目编译成dll？
还是说 依赖库 opencv或onnxruntime的编译方法？
这2个依赖库，由另外两个仓库编译，所有编译脚本都在仓库里找
https://github.com/RapidAI/OnnxruntimeBuilder
https://github.com/RapidAI/OpenCVBuilder

**Comment by yupd** [comment]
> 
build.md 中也有说明，我漏看了，谢谢！
